dist: xenial
sudo: required
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
env:
  - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - pip install --user -U pip
  - pip install --user cmake ninja conan

script:
  - conan install -if build . --build=missing
  - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -Bbuild .
  - cmake --build build
