dist: xenial
sudo: required
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="PATH=$HOME/Library/Python/2.7/bin:$PATH && CC=clang && CXX=clang++"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - g++-6
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - pip install --user -U pip
  - pip install --user cmake ninja conan

script:
  - conan install -if build . --build=missing
  - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -Bbuild .
  - cmake --build build
